# Generated by Django 5.0.3 on 2024-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='annual_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
