# Generated by Django 5.0.3 on 2024-04-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_item_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
